package com.yingyi.test;

public class VimTest {
    public static void main(String[] args) {
        System.out.println("Hello World!");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("vim editor");
        System.out.println("vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("user tssfsdtssfsdtssfsdtssfsdtssfsdtssfsdtssfsdtssfsd");
        System.out.println("try to study Vim editor");
        System.out.println("use visual model to  select context to change");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("use ci\" to change context in quotes");
        System.out.println("use to change context in quotes");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");
        System.out.println("try to study Vim editor");

        System.out.println("test");

        String a = "sadf";
        String b = "a";
        System.out.println(a.concat(b));
    }
}



